provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  wf-director:
    lang: Dockerfile
    handler: ./wf-director
    image: ibo1986/wf-director:latest
    environment:
      fprocess: "node index.js"
      gateway_url: http://gateway:8080/function/
      combine_output: false
      write_debug: true
      read_timeout: 25s
      write_timeout: 25s
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
      topic: newjob
              
  getjob:
    lang: Dockerfile
    handler: ./getjob
    image: ibo1986/getjob:latest
    environment:
      fprocess: "node index.js"
      content_type: application/json
      combine_output: false
      write_debug: true
      read_timeout: 25s
      write_timeout: 25s
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
  getxml:
    lang: Dockerfile
    handler: ./getxml
    image: ibo1986/getxml:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
  
  setpositionandpath:
    lang: Dockerfile
    handler: ./setpositionandpath
    image: ibo1986/setpositionandpath:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s 
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
 
  wunode:
    lang: Dockerfile
    handler: ./wunode
    image: ibo1986/wunode:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
   
  updatejob:
    lang: Dockerfile
    handler: ./updatejob
    image: ibo1986/updatejob:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s 
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
   
  modify:
    lang: Dockerfile
    handler: ./modify
    image: ibo1986/modify:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s 
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
  
  donejob:
    lang: Dockerfile
    handler: ./donejob
    image: ibo1986/donejob:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s 
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
  getparameter:
    lang: Dockerfile
    handler: ./getparameter
    image: ibo1986/getparameter:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s 
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50
  finishjob:
    lang: Dockerfile
    handler: ./finishjob
    image: ibo1986/finishjob:latest
    environment:
      fprocess: "node index.js"
      read_timeout: 25s
      write_timeout: 25s 
      content_type: application/json
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 50