<?xml version="1.0" encoding="ISO-8859-1"?>
<DPF>
  <config
    COMMAND="*"
    DPFINT-FileLinks="*"
    DPFINT-Icon="*"
    DPFINT-Type="*"
    IGNOREEXITCODE="*"
    INTERNALNAME="*"
    LOGLEVEL="*"
    LOGNAME="*"
    LOGSTDOUT="*"
    NAME="*"
    PROJECT="*"
    Status="*"
    THREADS="*"
    TYPE="*"
    VERSION="*"
    >
    <workingunits
      COMMAND=""
      DPFINT-FileLinks=""
      DPFINT-Icon=""
      DPFINT-Type=""
      IGNOREEXITCODE=""
      INTERNALNAME=""
      LOGLEVEL=""
      LOGNAME=""
      LOGSTDOUT=""
      NAME=""
      PROJECT=""
      Status=""
      THREADS=""
      TYPE=""
      VERSION=""
      >
      <sapcheckout
        COMMAND="%DPFSRV%/scripts/sap/sapcheckout.pl -parfile %PARFILENAME%"
        DPFINT-FileLinks="doc://:/%DPFSRV%/scripts/sap/sapcheckout.pl"
        DPFINT-Icon="doc://:/wu.gif"
        DPFINT-Type="StationDescription"
        ENVIRONMENTS=""
        IGNOREEXITCODE="N"
        LOGLEVEL="LOG_INFO"
        LOGNAME="sapcheckout"
        LOGSTDOUT="Y"
        NAME="SAP Checkout with RLI"
        PROJECT="SAP"
        Status="Running"
        THREADS="1"
        TYPE="WUSystemCall"
        VERSION="$Id: wu-sapcheckout.customer.xml,v 1.4 2007/03/28 10:39:38 ch Exp $"
        >
        <DEFAULTS
          DPFINT-Icon="doc://:/defaults.gif"
          IGNORE_MISSING_SAP_DOCUMENTS="Y"
          WU_ENABLE_DEBUG_LOOP="N"
          />
        <INPUT
          DPFINT-Icon="doc://:/wu-input.gif"
          IGNORE_MISSING_SAP_DOCUMENTS="*"
          WU_ENABLE_DEBUG_LOOP="*"
          >
          <CAD_NETADDRESS
            TYPE="TEXT"
            />
          <CHECKOUT_FILENAME
            TYPE="TEXT"
            />
          <CURRFILENAME
            TYPE="TEXT"
            />
          <IGNORE_MISSING_SAP_DOCUMENTS
            DEFAULT="Y"
            TYPE="CHECK"
            >
            <RANGE
              VALUE1="false=N"
              VALUE2="true=Y"
              />
          </IGNORE_MISSING_SAP_DOCUMENTS>
          <JOBDIR
            TYPE="TEXT"
            />
          <SAPCHECKOUT_MAP_EXTENSIONS
            TYPE="TEXT"
            />
          <TESTDIRDUMMYFILES
            TYPE="TEXT"
            />
          <USECHECKOUTDUMMY
            TYPE="CHECK"
            >
            <RANGE
              VALUE1="false=N"
              VALUE2="true=Y"
              />
          </USECHECKOUTDUMMY>
          <WFNAME
            TYPE="TEXT"
            />
          <WU_ENABLE_DEBUG_LOOP
            DEFAULT="N"
            TYPE="CHECK"
            >
            <RANGE
              VALUE1="false=N"
              VALUE2="true=Y"
              />
          </WU_ENABLE_DEBUG_LOOP>
        </INPUT>
      </sapcheckout>
    </workingunits>
  </config>
</DPF>
