version: '3.2'
services:
  rabbitqueue:
    image: rabbitmq:3.7.4
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
    networks:
      - streaming

  localconnector:
    image: ibo1986/localconnector:11
   # environment:
    #  MQ_HOST: "rabbitqueue"
     # MQ_PORT: "5672"
      #MQ_USER: "user"
     # MQ_PASS: "pass"
    networks:
      - streaming

  connector:
    image: templum/rabbitmq-connector:latest
    environment:
      MQ_TOPICS: "newjob"
      MQ_HOST: "rabbitqueue"
      MQ_PORT: "5672"
      MQ_USER: "user"
      MQ_PASS: "pass"
      FAAS_GW_URL: "http://gateway:8080"
    networks:
      - func_functiontest
      - streaming

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functiontest:
    external: true

