<?xml version="1.0" encoding="ISO-8859-1"?>
<DPF>
  <config>
    <workingunits>
      <FileTransfer.sendFtp
        COMMAND="%DPFSRV%/scripts/filetransfer/sendftp.pl -parfile %PARFILENAME%"
        DPFINT-FileLinks="doc://:/%DPFSRV%/scripts/filetransfer/sendftp.pl"
        DPFINT-Icon="doc://:/wu.gif"
        DPFINT-Type="StationDescription"
        IGNOREEXITCODE="N"
        LOGLEVEL="LOG_INFO"
        LOGNAME=""
        LOGSTDOUT="Y"
        NAME="Send FTP"
        PROJECT="FileTransfer"
        Status="Running"
        THREADS="1"
        TYPE="WUSystemCall"
        VERSION="$Id: wu-sendftp.customer.xml,v 1.3 2007/03/28 10:39:37 ch Exp $"
        >
        <DEFAULTS
          DPFINT-Icon="doc://:/defaults.gif"
          FTP_DEBUG="N"
          FTP_HOSTNAME="customize_hostname"
          FTP_PASSWORD="customize_password"
          FTP_USERNAME="customize_username"
          WU_ENABLE_DEBUG_LOOP="N"
          />
        <INPUT
          DPFINT-Icon="doc://:/wu-input.gif"
          FTP_HOSTNAME="*"
          FTP_OVERWRITE="*"
          FTP_PASSWORD="*"
          FTP_RETRY="*"
          FTP_SOURCE_PROPERTIES="*"
          FTP_TARGETDIR="*"
          FTP_TARGET_PROPERTIES="*"
          FTP_USERNAME="*"
          WU_ENABLE_DEBUG_LOOP="*"
          >
          <CURRFILENAME
            TYPE="TEXT"
            />
          <FTP_DEBUG
            DEFAULT="N"
            TYPE="CHECK"
            >
            <RANGE
              VALUE1="false=N"
              VALUE2="true=Y"
              />
          </FTP_DEBUG>
          <FTP_HOSTNAME
            DEFAULT="customize_hostname"
            TYPE="TEXT"
            />
          <FTP_OVERWRITE
            TYPE="TEXT"
            />
          <FTP_PASSWORD
            DEFAULT="customize_password"
            TYPE="TEXT"
            />
          <FTP_RETRY
            TYPE="TEXT"
            />
          <FTP_SOURCE_PROPERTIES
            TYPE="TEXT"
            />
          <FTP_TARGETDIR
            TYPE="TEXT"
            />
          <FTP_TARGET_PROPERTIES
            TYPE="TEXT"
            />
          <FTP_USERNAME
            DEFAULT="customize_username"
            TYPE="TEXT"
            />
          <JOBDIR
            TYPE="TEXT"
            />
          <WU_ENABLE_DEBUG_LOOP
            DEFAULT="N"
            TYPE="CHECK"
            >
            <RANGE
              VALUE1="false=N"
              VALUE2="true=Y"
              />
          </WU_ENABLE_DEBUG_LOOP>
        </INPUT>
      </FileTransfer.sendFtp>
    </workingunits>
  </config>
</DPF>
